apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{.Chart.Name}}-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        {{- if .Values.global.aws.secretStoreServiceAccount.enabled }}
        jwt:
          serviceAccountRef:
            name: {{ .Values.global.aws.secretStoreServiceAccount.name }}
